# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6174ed62bf03abba97aab90d2d4fdab4"
name = "store-cntr"
handle = "store-cntr"
application_url = "https://stability-val-icons-bidding.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "plowhearth-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://stability-val-icons-bidding.trycloudflare.com/auth/callback",
  "https://stability-val-icons-bidding.trycloudflare.com/auth/shopify/callback",
  "https://stability-val-icons-bidding.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
